---
- hosts: localhost
  vars: 
    inv_file: /home/testuser/redhat-ansible/vars/inv.txt
  tasks: 
  - name: Create file
    file: path={{ inv_file }} state=touch
  - name: generate inv
    lineinfile: 
       path: "{{ inv_file }}"
       line: "{{ groups['labservers']|join(' ') }}"
