---
- hosts: ansiblenode1.example.local
  become: yes
  tasks: 
  - name: Create a file
    file: path=/tmp/newfile state=touch
    register: output
  - debug: msg="Register output is {{output}}"
  - name: edit file
    lineinfile: path=/tmp/newfile line="{{output}}"
